### ISSUE TITLE
Read more button for blog post are not stylized

### ISSUE THREAD

**Issue by pauloxnet** [pythonitalia/pycon#3101]
The "Read more" button in the lists of posts in the Blog section are not stylized and is confusing with the abstract text.

I don't know how is organized the css code so I'll add here an attempt do add style for this button and attach here a screenshot with a stylized version and with the original plain version.

```CSS
readmore {
  display: block;
  border: 4px black solid;
  width: fit-content;
  padding: 0.5rem;
  margin-top: 1rem;
  background-color: var(--theme-ui-colors-yellow);
}
```

![Read more butto demo for Blog PyCon Italia](https://user-images.githubusercontent.com/521097/199503957-a9035ea5-e728-47ae-8913-d48ceb1816e6.png)
